### PR TITLE
gh-page index.html file

### PR DESCRIPTION
**Pull request by iddle254**
image
image
image
image

You have been invited to view my page

### CODE REVIEW

**Comment by iddle254** [comment]
image

**Comment by kamaudan** [comment]
Looks awesome, you can reduce the borders so  that you html elements  such as table can  blend in seamlessly.

**Comment by davishooly** [comment]
awesome keep up with the good work

**Comment by iddle254** [comment]
image
image
image
image
Hi! Please checkout my designs. Fell free to drop a comment

**Pull request merged**
